name: CI
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  list-modules:
    name: list-modules

    runs-on: ubuntu-latest

    outputs:
      modules: ${{ steps.modules.outputs.modules }}

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: make list-modules
      id: modules
      run: echo "modules=$(make list-modules)" >> $GITHUB_OUTPUT

  golangci-lint-matrix:
    name: golangci-lint [${{ matrix.working-directory }}]
    
    runs-on: ubuntu-latest

    needs:
      - list-modules
    
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJSON(needs.list-modules.outputs.modules) }}
    
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
      - name: Calculate go version
        id: vars
        run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # tag=v9.2.0
        with:
          version: v2.3.0
          working-directory: ${{matrix.working-directory}}

  golangci-lint: # aggregate the results of the matrix job. This we can depend on in the branch protection rule.
    name: golangci-lint
    runs-on: ubuntu-latest
    needs:
    - golangci-lint-matrix
    if: (failure() || success()) && !contains(needs.golangci-lint-matrix.result, 'skipped')
    steps:
    - name: noop
      run: exit 1
      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')

  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: make test
      run: MAKEFLAGS="-s" make test

  verify-modules:
    name: make verify-modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: make verify-modules
      run: MAKEFLAGS="-s" make verify-modules
